-- CreateTable
CREATE TABLE "ART" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "responsavel" TEXT NOT NULL,
    "titulo" TEXT NOT NULL,
    "empresa" TEXT NOT NULL,
    "contratante" TEXT NOT NULL,
    "endereco_contr" TEXT NOT NULL,
    "cidade_contr" TEXT NOT NULL,
    "uf_contr" TEXT NOT NULL,
    "cep_contr" TEXT NOT NULL,
    "cpf_cnpj_contr" TEXT NOT NULL,
    "valor_contr" REAL NOT NULL,
    "proprietario" TEXT NOT NULL,
    "endereco_prop" TEXT NOT NULL,
    "cidade_prop" TEXT NOT NULL,
    "uf_prop" TEXT NOT NULL,
    "cep_prop" TEXT NOT NULL,
    "cpf_cnpj_prop" TEXT NOT NULL,
    "data_inicio" DATETIME NOT NULL,
    "data_termino" DATETIME NOT NULL,
    "custo_obra" REAL NOT NULL,
    "dimensao_obra" TEXT NOT NULL,
    "memorial" TEXT NOT NULL,
    "observacoes" TEXT NOT NULL,
    "situacao" TEXT NOT NULL,
    "acessibilidade" BOOLEAN NOT NULL,
    "entidade_classe" TEXT NOT NULL
);
